version: '3.8'

services:
  app:
    image: hugomazeas/arc_tracker:latest
    container_name: archery-tracker
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./database:/var/www/database
      - ./storage:/var/www/storage
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    command: >
      sh -c "php artisan key:generate --force &&
             php artisan migrate --force &&
             /usr/bin/supervisord -c /etc/supervisord.conf"
